---
title: "RIS Desk Tracker"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: "images/treeWhite.png"
    favicon: "images/favicon.png"
    includes:
      in_header: "www/styles.css"
runtime: shiny
---

```{r}
source("./R/prep.R")
```

Sidebar {.sidebar}
=======================================================================

### Select Filters

```{r}
dateRangeInput("dates", label = h4("Dates"), start = Sys.Date()-30, end = Sys.Date())
textOutput("dateValidate")
output$dateValidate <- renderText({validate(need(input$dates[2] >= input$dates[1], "End Date is earlier than Start Date."))})

selectInput("calculation", label = h4("Calculation to Use"), choices = c("Sum" = "sum", "Mean" = "mean", "Median" = "median", "Max" = "max", "Min" = "min"), selected = "mean")

uniqueMode <- c(unique(factor(df1$mode) %>% as.vector()))
uniqueType <- c(unique(factor(df1$type) %>% as.vector()))
uniqueRef <- c(unique(factor(df1$referral) %>% as.vector()))
uniqueTerm <- c(unique(factor(df1$term) %>% as.vector()))

checkboxGroupInput("mode", label = h4("Mode of Interaction"), choices = uniqueMode, selected = uniqueMode)
checkboxInput(inputId = "selectAllMode", label = "Select/Unselect All (Mode)", value = TRUE)


checkboxGroupInput("type", label = h4("Type of Interaction"), choices = uniqueType, selected = uniqueType)
checkboxInput("selectAllType", "Select/Unselect All (Type)", value = TRUE)

checkboxGroupInput("referral", label = h4("Referral"), choices = uniqueRef, selected = uniqueRef)
checkboxInput("selectAllRef", "Select/Unselect All (Referral)", value = TRUE)

checkboxGroupInput("term", label = h4("Academic Term"), choices = uniqueTerm, selected = uniqueTerm)
checkboxInput("selectAllTerm", "Select/Unselect All (Term)", value = TRUE)

reactive({ 
  updateCheckboxGroupInput(session, "mode", choices = uniqueMode, selected = if(input$selectAllMode) uniqueMode)
  updateCheckboxGroupInput(session, "type", choices = uniqueType, selected = if(input$selectAllType) uniqueType)
  updateCheckboxGroupInput(session, "referral", choices = uniqueRef, selected = if(input$selectAllRef) uniqueRef)
  updateCheckboxGroupInput(session, "term", choices = uniqueTerm, selected = if(input$selectAllTerm) uniqueTerm)
  })
```

Overview
=======================================================================
```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Day and Time
```{r}

d3heatmapOutput("ovHeat")

output$ovHeat <- renderD3heatmap({
  d3heatmap(d3HeatData(), Rowv = FALSE, Colv = FALSE, col = c("#60e9dc", "#2f4b4e"), show_grid = 5)
})
```

### Heatmap Data
```{r}
tableOutput("ovHeatTable") 

output$ovHeatTable <- renderTable({d3HeatData()})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### By Time
```{r}
plotlyOutput("ovLines")

output$ovLines <- renderPlotly({plotLines(linesData())})
```

### By Weekday
```{r}
plotlyOutput("ovDayLines")

output$ovDayLines <- renderPlotly({plotLines(linesData("weekday"), "weekday")})
```

By Mode of Interaction
=======================================================================
```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Time
```{r}
plotlyOutput("modeLines")

output$modeLines <- renderPlotly({plotLines(linesData("mode"), "mode")})

```

### By Weekday
```{r}
plotlyOutput("modeBars")

output$modeBars <- renderPlotly({plotBars(timeData("mode", timeFrame = "weekday"), fillGroup = "mode", timeFrame = "weekday")})
```

### By Month
```{r}
plotlyOutput("modeMonth")

output$modeMonth <- renderPlotly({plotBars(timeData("mode", timeFrame = "month"), fillGroup = "mode", timeFrame = "month")})
```

### By Term
```{r}
plotlyOutput("modeTerm")

output$modeTerm <- renderPlotly({plotBars(timeData("mode", timeFrame = "term"), fillGroup = "mode", timeFrame = "term")})
```

### By Year
```{r}
plotlyOutput("modeYear")

output$modeYear <- renderPlotly({plotBars(timeData("mode", timeFrame = "year"), fillGroup = "mode", timeFrame = "year")})
```

Row
-----------------------------------------------------------------------
### Data

```{r}
output$modeData <- renderTable({heatData("mode")})

tableOutput("modeData")
```

By Type of Interaction
=======================================================================

```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Time
```{r}
plotlyOutput("typeLines")

output$typeLines <- renderPlotly({plotLines(linesData("type"), "type")})

```

### By Weekday
```{r}
plotlyOutput("typeBars")

output$typeBars <- renderPlotly({plotBars(timeData("type", timeFrame = "weekday"), fillGroup = "type", timeFrame = "weekday")})
```

### By Month
```{r}
plotlyOutput("typeMonth")

output$typeMonth <- renderPlotly({plotBars(timeData("type", timeFrame = "month"), fillGroup = "type", timeFrame = "month")})
```

### By Term
```{r}
plotlyOutput("typeTerm")

output$typeTerm <- renderPlotly({plotBars(timeData("type", timeFrame = "term"), fillGroup = "type", timeFrame = "term")})
```

### By Year
```{r}
plotlyOutput("typeYear")

output$typeYear <- renderPlotly({plotBars(timeData("type", timeFrame = "year"), fillGroup = "type", timeFrame = "year")})
```

Row
-----------------------------------------------------------------------
### Data

```{r}

output$typeheatData <- renderTable({heatData("type")})
tableOutput("typeheatData")
```

By Referral
=======================================================================

```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Time
```{r}
plotlyOutput("refLines")

output$refLines <- renderPlotly({plotLines(linesData("referral"), "referral")})

```

### By Weekday
```{r}
plotlyOutput("refBars")

output$refBars <- renderPlotly({plotBars(timeData("referral", timeFrame = "weekday"), fillGroup = "referral", timeFrame = "weekday")})
```

### By Month
```{r}
plotlyOutput("refMonth")

output$refMonth <- renderPlotly({plotBars(timeData("referral", timeFrame = "month"), fillGroup = "referral", timeFrame = "month")})
```

### By Term
```{r}
plotlyOutput("refTerm")

output$refTerm <- renderPlotly({plotBars(timeData("referral", timeFrame = "term"), fillGroup = "referral", timeFrame = "term")})
```

### By Year
```{r}
plotlyOutput("refYear")

output$refYear <- renderPlotly({plotBars(timeData("referral", timeFrame = "year"), fillGroup = "referral", timeFrame = "year")})
```

Row
-----------------------------------------------------------------------
### Data

```{r}

output$refheatData <- renderTable({heatData("referral")})
tableOutput("refheatData")
```


Totals
=======================================================================

```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Time
```{r}
plotlyOutput("totalLines")

output$totalLines <- renderPlotly({plotLines(linesData())})

```

### By Weekday
```{r}
plotlyOutput("totalBars")

output$totalBars <- renderPlotly({plotBars(timeData(timeFrame = "weekday"), timeFrame = "weekday")})
```

### By Month
```{r}
plotlyOutput("totalMonth")

output$totalMonth <- renderPlotly({plotBars(timeData(timeFrame = "month"), timeFrame =  "month")})
```

### By Term
```{r}
plotlyOutput("totalTerm")

output$totalTerm <- renderPlotly({plotBars(timeData(timeFrame = "term"), timeFrame = "term")})
```

### By Year
```{r}
plotlyOutput("totalYear")

output$totalYear <- renderPlotly({plotBars(timeData(timeFrame = "year"), timeFrame = "year")})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Daily Totals
```{r}

output$totalDaily <- renderPlotly({plotBars(dailyData(), timeFrame = "day")})
plotlyOutput("totalDaily")
```

### Data

```{r}

output$totalHeatData <- renderTable({dailyData()})
tableOutput("totalHeatData")
```

Raw Data
=======================================================================

Row
-----------------------------------------------------------------------
### Raw Data
```{r}
output$df <- renderTable(df())
tableOutput("df")
```


```{r}

# Get the calculation (mean, median, etc.) from input
calc <- reactive({ calc <- match.fun(as.character(input$calculation)) })

# Get our raw data as reactive, filtered by the dates and selections on the sidebar
df <- reactive({
  df <- df1 %>%
    filter(as.Date(date_time) >= as.Date(input$dates[1]) & as.Date(date_time) <= as.Date(input$dates[2])) %>%
    filter(mode %in% input$mode & type %in% input$type & term %in% input$term & referral %in% input$referral)
})

# Turn data into a matrix suitable for the d3HeatMap package
d3HeatData <- reactive({
  df <- linesData("weekday") %>%
    spread(hour, value)
  row.names(df) <- as.character(as.factor(df$weekday))
  df <- data.matrix(df)
  df <- df[,2:ncol(df)]
  return(df)
})

linesData <- function(x = NULL) {
  df <- df()
  groups1 <- c("day", "hour")
  groups2 <- "hour"
  if(!is.null(x)){
    groups1 <- c(groups1, x)
    groups2 <- c(groups2, x)
  }
  if((!is.null(x)) && (x == "weekday")){
    df <- df %>%
      mutate_(weekday = "lubridate::wday(date_time, label = TRUE)")
  }
  df <- df %>%
    mutate_(day = "as.character.Date(lubridate::floor_date(as.Date(date_time), 'day'))", hour = "lubridate::hour(date_time)") %>%
    group_by_(.dots = groups1) %>%
    summarize(value = sum(value)) %>%
    group_by_(.dots = groups2) %>%
    summarize(value = calc()(value))
  if(!is.null(x)) {
    df %>%
      filter_(lazyeval::interp(~ var != "NA", var = as.name(x)))
  }
  return(df)
}

heatData <- function(x) {
  df <- df() %>%
    group_by_(x, day = "as.character.Date(lubridate::floor_date(as.Date(date_time), 'day'))", weekday = "lubridate::wday(date_time, label = TRUE)", hour = "lubridate::hour(date_time)") %>%
    summarize(value = sum(value)) %>%
    group_by_(x, "weekday", "hour") %>%
    summarize(value = calc()(value))
  return(df)
}

plotLines <- function(df, lineColor = NULL) {

  p <- ggplot(data = df, aes(x = hour, y = value)) +
    labs(x = "Time", y = "Number of Interactions")

  if(!is.null(lineColor)) {
    p <- p +
      geom_line(aes_string(color = lineColor)) +
      scale_color_discrete(guide = guide_legend(title = stringr::str_to_title(lineColor)))
  } else {
    p <- p +
      geom_line()
  }
  
  ggplotly(p)
}

dailyData <- function() {
  df <- df()
  
  df <- df %>%
    mutate_(day = "as.character.Date(lubridate::floor_date(as.Date(date_time), 'day'))") %>%
    group_by(day) %>%
    summarize(value = sum(value))
}

timeData <- function(x = NULL, timeFrame = "weekday") {

  df <- df()

  groups1 <- c("day", timeFrame)
  groups2 <- timeFrame
  

  if(!is.null(x)){
    groups1 <- c(groups1, x)
    groups2 <- c(groups2, x)
  }
  
  if (timeFrame == "weekday"){
    df <- df %>%
      mutate_(day = "as.character.Date(lubridate::floor_date(as.Date(date_time), 'day'))", weekday = "lubridate::wday(date_time, label = TRUE)")
  } else if (timeFrame == "month") {
    df <- df %>%
      mutate_(day = "as.character.Date(lubridate::floor_date(as.Date(date_time), 'day'))", month = "lubridate::month(date_time, label = TRUE)")    
  } else if (timeFrame == "term") {
     df <- df %>%
      mutate_(day = "as.character.Date(lubridate::floor_date(as.Date(date_time), 'day'))", "term")   
  } else if (timeFrame == "year") {
    df <- df %>%
      mutate_(day = "as.character.Date(lubridate::floor_date(as.Date(date_time), 'day'))", year = "as.factor(lubridate::year(date_time))")
  }
  
  df <- df %>%
    group_by_(.dots = groups1) %>%
    summarize(value = sum(value)) %>%
    group_by_(.dots = groups2) %>%
    summarize(value = calc()(value))
  
  if(!is.null(x)) {
    df <- df %>%
      filter_(lazyeval::interp(~ var != "NA", var = as.name(x)))
  }
  return(df)
}

plotBars <- function(df, fillGroup = NULL, timeFrame){
  p <- ggplot(data = df, aes_string(x = timeFrame, y = "value")) +
      labs(x = stringr::str_to_title(timeFrame), y = "Interactions per Day")
  if(!is.null(fillGroup)){
    p <- p +
      geom_bar(aes_string(fill = fillGroup), stat = "identity", position = "dodge") +
      geom_text(aes_string(label = quote(round(value, 2)), group = fillGroup), position = position_dodge(width = 1), vjust = 0) + 
      scale_fill_discrete(guide = guide_legend(title = stringr::str_to_title(fillGroup)))
  } else {
    p <- p +
      geom_bar(fill = "steelblue", stat = "identity") +
      geom_text(aes_string(label = quote(round(value, 2))), vjust = 0)
  }
  if (timeFrame == "day") {
    p <- p +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
      labs(x = " ")
  }
  ggplotly(p)
}

plotHeat <- function(df) {
  p <- ggplot(data = df, aes(x = hour, y = weekday))
  p <- p +
    geom_tile(aes(fill = value), color = "black") +
    scale_fill_gradient(low="white", high="steelblue", guide=guide_colorbar(title=expression(paste("Number of Interactions")))) +
    labs(x="Hour", y="Weekday")
  return(p)
}

```
