---
title: "RIS Desk Tracker"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    style: styles.css 
runtime: shiny
---

```{r}
source("../R/prep.R")
```

Sidebar {.sidebar}
=======================================================================

### Select Filters

```{r}
dateRangeInput("dates", label = h4("Dates"), start = Sys.Date()-30, end = Sys.Date())
textOutput("dateValidate")

selectInput("calculation", label = h4("Calculation to Use"), choices = c("Sum" = "sum", "Mean" = "mean", "Median" = "median", "Max" = "max", "Min" = "min"), selected = "mean")

checkboxGroupInput("mode", label = h4("Mode of Interaction"), choices = c(unique(factor(df1$mode) %>% as.vector())), selected = c(unique(factor(df1$mode) %>% as.vector())))

checkboxGroupInput("type", label = h4("Type of Interaction"), choices = c(unique(factor(df1$type) %>% as.vector())), selected = c(unique(factor(df1$type) %>% as.vector())))

checkboxGroupInput("referral", label = h4("Referral"), choices = c(unique(factor(df1$referral) %>% as.vector())), selected = c(unique(factor(df1$referral) %>% as.vector())))

checkboxGroupInput("term", label = h4("Academic Term"), choices = c(unique(factor(df1$term) %>% as.vector())), selected = c(unique(factor(df1$term) %>% as.vector())))
```

Overview
=======================================================================
```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### Day and Time
```{r}

d3heatmapOutput("ovHeat")

output$ovHeat <- renderD3heatmap({
  d3heatmap(d3HeatData(), Rowv = FALSE, Colv = FALSE, col = c("#60e9dc", "#2f4b4e"), show_grid = 5)
})
```

### Heatmap Data
```{r}
tableOutput("ovHeatTable") 

output$ovHeatTable <- renderTable({d3HeatData()})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------
### By Time
```{r}
plotlyOutput("ovLines")

output$ovLines <- renderPlotly({
  p <- ggplot(data = ovLineData(), aes(x = hour, y = value))
  p <- p +
    geom_line(size = 1) +
    geom_point() +
#    geom_text(aes(label = round(value, 2)), vjust = -1) + 
    guides(color = "none") + 
    labs(x = "Time", y = "Number of Interactions")
  ggplotly(p)
})
```

### By Weekday
```{r}
plotlyOutput("ovDayLines")

output$ovDayLines <- renderPlotly({
  p <- ggplot(data = ovData(), aes(x = hour, y = value))
  p <- p +
    geom_line(aes(color = weekday), size = 1) +
    geom_point(aes(color = weekday)) +
    geom_text(aes(label = round(value, 2)), vjust = -1) + 
    scale_color_discrete(guide = guide_legend(title = "Weekday")) +
    labs(x = "Time", y = "Number of Interactions")
  ggplotly(p)
})
```

By Mode of Interaction
=======================================================================
```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Time
```{r}
plotOutput("modeLines")

output$modeLines <- renderPlot({plotLines(linesData("mode"), "mode")})

```

### By Weekday
```{r}
plotOutput("modeBars")

output$modeBars <- renderPlot({plotBars(barsData("mode"), "mode")})
```

Row
-----------------------------------------------------------------------
### Data

```{r}
output$modeData <- renderTable({heatData("mode")})

tableOutput("modeData")
```

By Type of Interaction
=======================================================================

```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Time
```{r}
plotOutput("typeLines")

output$typeLines <- renderPlot({plotLines(linesData("type"), "type")})

```

### By Weekday
```{r}
plotOutput("typeBars")

output$typeBars <- renderPlot({plotBars(barsData("type"), "type")})
```

Row
-----------------------------------------------------------------------
### Data

```{r}

output$typeheatData <- renderTable({heatData("type")})
tableOutput("typeheatData")
```

By Referral
=======================================================================

```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Time
```{r}
plotOutput("refLines")

output$refLines <- renderPlot({plotLines(linesData("referral"), "referral")})

```

### By Weekday
```{r}
plotOutput("refBars")

output$refBars <- renderPlot({plotBars(barsData("referral"), "referral")})
```

Row
-----------------------------------------------------------------------
### Data

```{r}

output$refheatData <- renderTable({heatData("referral")})
tableOutput("refheatData")
```


Raw Data
=======================================================================

Row
-----------------------------------------------------------------------
### Raw Data
```{r}
output$df <- renderTable(df())
tableOutput("df")
```


```{r}


calc <- reactive({ calc <- match.fun(as.character(input$calculation)) })

df <- reactive({
  df <- df1 %>%
    filter(as.Date(date_time) >= as.Date(input$dates[1]) & as.Date(date_time) <= as.Date(input$dates[2])) %>%
    filter(mode %in% input$mode & type %in% input$type & term %in% input$term & referral %in% input$referral)
})

output$dateValidate <- renderText({validate(need(input$dates[2] >= input$dates[1], "End Date is earlier than Start Date."))})

d3HeatData <- reactive({
  df <- ovData() %>%
    spread(hour, value)
  row.names(df) <- as.character(as.factor(df$weekday))
  df <- data.matrix(df)
  df <- df[,2:ncol(df)]
  return(df)
})

ovLineData <- reactive({
  df <- df() %>%
    group_by_(day = "as.Date(date_time)", weekday = "lubridate::wday(date_time, label = TRUE)", hour = "lubridate::hour(date_time)") %>%
    summarize(value = sum(value)) %>%
    group_by_("hour") %>%
    summarize(value = calc()(value))
  return(df)
})

ovData <- reactive({
  df <- df() %>%
    group_by_(day = "as.Date(date_time)", weekday = "lubridate::wday(date_time, label = TRUE)", hour = "lubridate::hour(date_time)") %>%
    summarize(value = sum(value)) %>%
    group_by_("weekday", "hour") %>%
    summarize(value = calc()(value))
  return(df)
})

linesData <- function(x) {
  df <- df() %>%
    group_by_(x, day = "as.Date(date_time)", hour = "lubridate::hour(date_time)") %>%
    summarize(value = sum(value)) %>%
    group_by_(x,"hour") %>%
    summarize(value = calc()(value)) %>%
    filter_(lazyeval::interp(~ var != "NA", var = as.name(x)))
  return(df)
}


heatData <- function(x) {
  df <- df() %>%
    group_by_(x, day = "as.Date(date_time)", weekday = "lubridate::wday(date_time, label = TRUE)", hour = "lubridate::hour(date_time)") %>%
    summarize(value = sum(value)) %>%
    group_by_(x, "weekday", "hour") %>%
    summarize(value = calc()(value))
  return(df)
}

plotLines <- function(df, lineColor) {
  p <- ggplot(data = df, aes(x = hour, y = value))
  p <- p +
    geom_line(aes_string(color = lineColor)) +
    geom_text(aes_string(label = quote(round(value, 2)))) + 
    scale_color_discrete(guide = guide_legend(title = paste(lineColor, "of Interaction"))) +
    labs(x = "Time", y = "Number of Interactions")
  return(p)
}

barsData <- function(x) {
  df <- df() %>%
    group_by_(x, day = "as.Date(date_time)", weekday = "lubridate::wday(date_time, label = TRUE)") %>%
    summarize(value = sum(value)) %>%
    group_by_(x, "weekday") %>%
    summarize(value = calc()(value)) %>%
    filter_(lazyeval::interp(~ var != "NA", var = as.name(x)))
}

plotBars <- function(df, fillGroup){
  p <- ggplot(data = df, aes(x = weekday, y = value))
  p <- p +
    geom_bar(aes_string(fill = fillGroup), stat = "identity", position = "dodge") +
    geom_text(aes_string(label = quote(round(value, 2)), group = fillGroup), position = position_dodge(width = 1), vjust = 0) + 
    scale_fill_discrete(guide = guide_legend(title = paste(fillGroup, "of Interaction"))) +
    labs(x = "Weekday", y = "Number of Interactions")
  return(p)
}

plotHeat <- function(df) {
  p <- ggplot(data = df, aes(x = hour, y = weekday))
  p <- p +
    geom_tile(aes(fill = value), color = "black") +
    scale_fill_gradient(low="white", high="steelblue", guide=guide_colorbar(title=expression(paste("Number of Interactions")))) +
    labs(x="Hour", y="Weekday")
  return(p)
}

```